default:
  image: python:3.8

stages:
  - test

linting_pytest:
  stage: test
  before_script:
  - pip install . -r requirements.txt
  - pip install flake8
  - pip install pytest
  - pip install pytest-cov
  script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

test_documentation:
  stage: test
  script:
  - cd docs
  - pip install . -r requirements.txt
  - sphinx-build -b html . ../public
