language: python
dist: bionic
python:
  - "3.8"
# command to install dependencies
install:
  - pip install . -r requirements.txt
  - pip install flake8
  - pip install pytest
  - pip install pytest-cov
script:
  # command to lint code
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
